In [1]:
import torch

## 创建张量

In [5]:
x = torch.arange(1, 12, 2)
x

tensor([ 1,  3,  5,  7,  9, 11])

> torch.arange(起始点, 结束点, 步长)

In [7]:
x = torch.zeros((3, 4))
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
x = torch.ones((3, 4))
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
x = torch.tensor([[1, 2, 3], [2, 3, 4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

## 张量运算

In [22]:
y = torch.tensor([[1, 2, 3]])
x * y

tensor([[ 1,  4,  9],
        [ 2,  6, 12]])

In [24]:
torch.cat((x, y), dim=0)

tensor([[1, 2, 3],
        [2, 3, 4],
        [1, 2, 3]])

### 广播机制

In [26]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a+b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [41]:
a = torch.arange(10).reshape((2, 5))
b = a.sum(axis=1, keepdims=True)
a, b, a / b

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[10],
         [35]]),
 tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
         [0.1429, 0.1714, 0.2000, 0.2286, 0.2571]]))

### 避免复制浪费算力

In [33]:
a = torch.arange(3).reshape((1, 3))
b = torch.arange(3).reshape((1, 3))
before = id(a)
a = a + b
before == id(a)

False

In [31]:
a = torch.arange(3).reshape((1, 3))
b = torch.arange(3).reshape((1, 3))
before = id(a)
a += b
before == id(a)

True

In [32]:
a = torch.arange(3).reshape((1, 3))
b = torch.arange(3).reshape((1, 3))
before = id(a)
a[:] = a + b
before == id(a)

True

### 矩阵乘法

In [54]:
a = torch.arange(20).reshape((4, 5))
b = torch.arange(20).reshape((5, 4))
a, b

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

In [47]:
torch.matmul(a, b)

tensor([[120, 130, 140, 150],
        [320, 355, 390, 425],
        [520, 580, 640, 700],
        [720, 805, 890, 975]])

In [60]:
x = torch.tensor([[1., 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]])
x.norm()

tensor(13.0384)