In [1]:
import torch

In [5]:
x = torch.arange(4.0)
x.requires_grad_(True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [6]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [10]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad == 4 * x

tensor([True, True, True, True])

In [19]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [27]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])