In [2]:
import math
import torch
from torch import nn
import numpy as np

In [2]:
from d2l import torch as d2l

In [3]:
X = torch.rand((2, 2, 4))
X

tensor([[[0.1426, 0.1004, 0.8218, 0.6086],
         [0.5597, 0.9375, 0.6896, 0.8433]],

        [[0.8815, 0.5641, 0.0222, 0.1297],
         [0.8922, 0.1492, 0.0218, 0.1234]]])

In [5]:
X_ = X.reshape(-1, X.shape[-1])
X_

tensor([[0.1426, 0.1004, 0.8218, 0.6086],
        [0.5597, 0.9375, 0.6896, 0.8433],
        [0.8815, 0.5641, 0.0222, 0.1297],
        [0.8922, 0.1492, 0.0218, 0.1234]])

In [3]:
label = torch.tensor([1, 2, 3])
label

tensor([1, 2, 3])

In [4]:
ones = torch.ones_like(label)
ones

tensor([1, 1, 1])